import datetime

def main():
    date = datetime.date.today().isoformat()
    title = f"sample-post-{date}"
    content = f"""---
title: "Sample Post {date}"
date: {date}T12:00:00Z
draft: false
---

This is a sample post generated by Python.
"""
    filename = f"content/posts/{date}-sample-post.md"
    with open(filename, "w") as f:
        f.write(content)
    print("Generated", filename)

if __name__ == "__main__":
    main()
